# .gitlab-ci.yml - Versión para Runner Local (UAO)
stages:
  - test
  - build

variables:
  IMAGE_NAME: "adrianfvr999/app_physicalrecovery_gitlab"
  IMAGE_TAG: "grupo2-1.0"

run_test:
  stage: test
  timeout: 2h
  tags:
    - uao-local
  image: python:3.11-slim
  before_script:
    # 1. Instalación de dependencias de sistema (OpenGL, Video, gRPC)
    - apt-get update && apt-get install -y --no-install-recommends curl libgl1 libglib2.0-0 ffmpeg make
    # 2. Instalación de uv
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="/root/.local/bin:$PATH"
    # 3. Instalación de librerías
    - uv sync --frozen
    # 4. Generación de archivos gRPC para el servidor de pose
    - uv run python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. pose.proto
    - mv pose_pb2.py src/ && mv pose_pb2_grpc.py src/
  script:
    # 5. Ejecución de los tests
    - uv run pytest

  cache:
    key:
      files:
        - pyproject.toml
        # Es agregar uv.lock como buenas practicas
        - uv.lock
    paths:
      # Antes teniamos todo .venv que son mas o menos 30K archivos, esto afecta, de modo que es mejor
      # almacenamos la informacion de uv, nos permite procesos de guardado/ descarga rápidos.
      - .uv-cache/


build_image:
  stage: build
  timeout: 2h
  tags:
    - uao-local
  image: docker:29.3.0-cli
  services:
    - name: docker:29.3.0-dind
      alias: docker
  variables:
    DOCKER_HOST: "unix:///runner/services/docker/docker.sock"
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
