services:
  grpc-server:
    image: adrianfvr999/app_physicalrecovery_gitlab:grupo2-1.0
    container_name: recovery-grpc-server
    ports:
      - "50051:50051"
    environment:
      - PYTHONUNBUFFERED=1
    command: uv run python src/grpc_server.py

  frontend:
    image: adrianfvr999/app_physicalrecovery_gitlab:grupo2-1.0
    container_name: recovery-frontend
    ports:
      - "8501:8501"
    depends_on:
      - grpc-server
    environment:
      - GRPC_SERVER_ADDRESS=grpc-server:50051
      - PYTHONUNBUFFERED=1
    command: uv run streamlit run app.py --server.address=0.0.0.0