# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pose.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npose.proto\x12\x04pose\"3\n\x0bPoseRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x05\"I\n\x08Keypoint\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\r\n\x05score\x18\x05 \x01(\x02\"+\n\x06Person\x12!\n\tkeypoints\x18\x01 \x03(\x0b\x32\x0e.pose.Keypoint\"\x7f\n\x0cPoseResponse\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12\x1c\n\x06people\x18\x02 \x03(\x0b\x32\x0c.pose.Person\x12\x15\n\rcurrent_angle\x18\x03 \x01(\x02\x12\x13\n\x0brepetitions\x18\x04 \x01(\x05\x12\x13\n\x0b\x66inal_score\x18\x05 \x01(\x02\x32\x46\n\x0bPoseService\x12\x37\n\nStreamPose\x12\x11.pose.PoseRequest\x1a\x12.pose.PoseResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSEREQUEST']._serialized_start=20
  _globals['_POSEREQUEST']._serialized_end=71
  _globals['_KEYPOINT']._serialized_start=73
  _globals['_KEYPOINT']._serialized_end=146
  _globals['_PERSON']._serialized_start=148
  _globals['_PERSON']._serialized_end=191
  _globals['_POSERESPONSE']._serialized_start=193
  _globals['_POSERESPONSE']._serialized_end=320
  _globals['_POSESERVICE']._serialized_start=322
  _globals['_POSESERVICE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
